server:
  port: 8080

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:h2:mem:reservation;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      platform: mysql
